#!/bin/bash
# Clone the specified version of clickhouse from didi's gitlab without a password.
# git clone -b 20.8.10.13-lts-100 https://gitlab+deploy-token-129:mMJYJVa5CsaeXNxfNYAV@git.xiaojukeji.com/datainfra-hadoop/didi-clickhouse.git
#set -e  # Exit the script if an error happens
set -x
whoami

cd $(dirname $0)
base_dir=`pwd`

function gitBranch()
{
  br=`git branch | grep "*"`
  echo ${br/* /}
}

if [ ${OE_BRANCH_NAME} ];  then
  # DiDi OE compiler system
  GIT_BRANCH=${OE_BRANCH_NAME}
elif [ ${CI_COMMIT_REF_NAME} ]; then
  # DiDi CI compiler system
  GIT_BRANCH=${CI_COMMIT_REF_NAME}
else
  GIT_BRANCH=`gitBranch`
fi

#CLICKHOUSE_VERSION="clickhouse-${GIT_BRANCH}"
CLICKHOUSE_VERSION=clickhouse-didi-`grep VERSION_MAJOR  cmake/autogenerated_versions.txt  | sed "s/[^0-9]//g"`
echo $CLICKHOUSE_VERSION
CLICKHOUSE_CONTRIB_ZIP="contrib-701.tar.gz"
GIFT_CLICKHOUSE_CONTRIB_DOWNLOAD_URL="http://10.88.128.23:8002/static/dlap_chaos/${CLICKHOUSE_CONTRIB_ZIP}"

continue=0

if [ "$1" = "-c" ];
then
  continue=1
fi

if [ "$continue" != 1 ];
then
  read -p "Are you sure to remove contrib and build directory?(y/n): " input
  echo "inptu: " $input
  if [ "$input" != 'y' ];
  then
      echo "build canceled!"
      exit 1
  fi

  # Remove clickhouse contrib dir
  rm -rf ./contrib

  # Download clickhouse contrib from didi's git.
  rm -rf /tmp/clickhouse-contrib
  wget ${GIFT_CLICKHOUSE_CONTRIB_DOWNLOAD_URL} -P "/tmp/clickhouse-contrib"
  tar -zxvf /tmp/clickhouse-contrib/${CLICKHOUSE_CONTRIB_ZIP} -C "${base_dir}/" > /dev/null

  rm -rf ./build
  mkdir ./build && cd ./build
  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-16 -DCMAKE_C_COMPILER=clang-16
else
  cd ./build
fi

ninja 

if [ "$1" = "-u" -o "$2" = "-u" ];
then
    # Create clickhouse package dir
    rm -rf /tmp/${CLICKHOUSE_VERSION}
    mkdir -p /tmp/${CLICKHOUSE_VERSION}/bin
    
    # Package clickhouse
    cd "${base_dir}"
    cp -R ./sbin/ /tmp/${CLICKHOUSE_VERSION}
    cp ./build/programs/clickhouse /tmp/${CLICKHOUSE_VERSION}/bin
    cp -d ./build/programs/clickhouse-server /tmp/${CLICKHOUSE_VERSION}/bin
    cp -d ./build/programs/clickhouse-client /tmp/${CLICKHOUSE_VERSION}/bin
    cp -d ./build/programs/clickhouse-copier /tmp/${CLICKHOUSE_VERSION}/bin
    cp -d ./build/programs/clickhouse-copier /tmp/${CLICKHOUSE_VERSION}/bin
    cd /tmp
    tar czvf "${CLICKHOUSE_VERSION}.tar.gz" ${CLICKHOUSE_VERSION}
    curl -X DELETE "http://10.88.128.23:8001/resource/dlap_chaos/${CLICKHOUSE_VERSION}.tar.gz"
    curl "http://10.88.128.23:8000/resource/dlap_chaos/${CLICKHOUSE_VERSION}.tar.gz" -X POST -F filecontent=@"${CLICKHOUSE_VERSION}.tar.gz"
    
    # OE output dir
    #cd "${base_dir}"
    #rm -rf ./output
    #mkdir ./output
    #mv ./build/programs/clickhouse ./output
    #mv ./build/programs/clickhouse-* ./output
fi

